// biome-ignore-all lint: generated by TanStack Router

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from "./routes/root";
import { Route as workflowsRouteImport } from "./routes/workflows";
import { Route as workRouteImport } from "./routes/work";
import { Route as spendRouteImport } from "./routes/spend";
import { Route as settingsRouteImport } from "./routes/settings";
import { Route as remindersRouteImport } from "./routes/reminders";
import { Route as pulseRouteImport } from "./routes/pulse";
import { Route as projectsRouteImport } from "./routes/projects";
import { Route as discoveryRouteImport } from "./routes/discovery";
import { Route as contentRouteImport } from "./routes/content";
import { Route as agentsRouteImport } from "./routes/agents";
import { Route as actionCenterRouteImport } from "./routes/action-center";
import { Route as indexRouteImport } from "./routes/index";
import { Route as workflowsDotworkflowIdRouteImport } from "./routes/workflows.$workflowId";
import { Route as projectsDotprojectIdRouteImport } from "./routes/projects.$projectId";
import { Route as messagesDotnewRouteImport } from "./routes/messages.new";
import { Route as channelsDotchannelIdRouteImport } from "./routes/channels.$channelId";
import { Route as channelsDotchannelIdDotpostsDotpostIdRouteImport } from "./routes/channels.$channelId.posts.$postId";

const workflowsRoute = workflowsRouteImport.update({
  id: "/workflows",
  path: "/workflows",
  getParentRoute: () => rootRouteImport,
} as any);
const workRoute = workRouteImport.update({
  id: "/work",
  path: "/work",
  getParentRoute: () => rootRouteImport,
} as any);
const spendRoute = spendRouteImport.update({
  id: "/spend",
  path: "/spend",
  getParentRoute: () => rootRouteImport,
} as any);
const settingsRoute = settingsRouteImport.update({
  id: "/settings",
  path: "/settings",
  getParentRoute: () => rootRouteImport,
} as any);
const remindersRoute = remindersRouteImport.update({
  id: "/reminders",
  path: "/reminders",
  getParentRoute: () => rootRouteImport,
} as any);
const pulseRoute = pulseRouteImport.update({
  id: "/pulse",
  path: "/pulse",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsRoute = projectsRouteImport.update({
  id: "/projects",
  path: "/projects",
  getParentRoute: () => rootRouteImport,
} as any);
const discoveryRoute = discoveryRouteImport.update({
  id: "/discovery",
  path: "/discovery",
  getParentRoute: () => rootRouteImport,
} as any);
const contentRoute = contentRouteImport.update({
  id: "/content",
  path: "/content",
  getParentRoute: () => rootRouteImport,
} as any);
const agentsRoute = agentsRouteImport.update({
  id: "/agents",
  path: "/agents",
  getParentRoute: () => rootRouteImport,
} as any);
const actionCenterRoute = actionCenterRouteImport.update({
  id: "/action-center",
  path: "/action-center",
  getParentRoute: () => rootRouteImport,
} as any);
const indexRoute = indexRouteImport.update({
  id: "/",
  path: "/",
  getParentRoute: () => rootRouteImport,
} as any);
const workflowsDotworkflowIdRoute = workflowsDotworkflowIdRouteImport.update({
  id: "/workflows/$workflowId",
  path: "/workflows/$workflowId",
  getParentRoute: () => rootRouteImport,
} as any);
const projectsDotprojectIdRoute = projectsDotprojectIdRouteImport.update({
  id: "/projects/$projectId",
  path: "/projects/$projectId",
  getParentRoute: () => rootRouteImport,
} as any);
const messagesDotnewRoute = messagesDotnewRouteImport.update({
  id: "/messages/new",
  path: "/messages/new",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdRoute = channelsDotchannelIdRouteImport.update({
  id: "/channels/$channelId",
  path: "/channels/$channelId",
  getParentRoute: () => rootRouteImport,
} as any);
const channelsDotchannelIdDotpostsDotpostIdRoute =
  channelsDotchannelIdDotpostsDotpostIdRouteImport.update({
    id: "/channels/$channelId/posts/$postId",
    path: "/channels/$channelId/posts/$postId",
    getParentRoute: () => rootRouteImport,
  } as any);

export interface FileRoutesByFullPath {
  "/": typeof indexRoute;
  "/action-center": typeof actionCenterRoute;
  "/agents": typeof agentsRoute;
  "/content": typeof contentRoute;
  "/discovery": typeof discoveryRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/spend": typeof spendRoute;
  "/work": typeof workRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesByTo {
  "/": typeof indexRoute;
  "/action-center": typeof actionCenterRoute;
  "/agents": typeof agentsRoute;
  "/content": typeof contentRoute;
  "/discovery": typeof discoveryRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/spend": typeof spendRoute;
  "/work": typeof workRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport;
  "/": typeof indexRoute;
  "/action-center": typeof actionCenterRoute;
  "/agents": typeof agentsRoute;
  "/content": typeof contentRoute;
  "/discovery": typeof discoveryRoute;
  "/projects": typeof projectsRoute;
  "/pulse": typeof pulseRoute;
  "/reminders": typeof remindersRoute;
  "/settings": typeof settingsRoute;
  "/spend": typeof spendRoute;
  "/work": typeof workRoute;
  "/workflows": typeof workflowsRoute;
  "/channels/$channelId": typeof channelsDotchannelIdRoute;
  "/messages/new": typeof messagesDotnewRoute;
  "/projects/$projectId": typeof projectsDotprojectIdRoute;
  "/workflows/$workflowId": typeof workflowsDotworkflowIdRoute;
  "/channels/$channelId/posts/$postId": typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath;
  fullPaths:
    | "/"
    | "/action-center"
    | "/agents"
    | "/content"
    | "/discovery"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/spend"
    | "/work"
    | "/workflows"
    | "/channels/$channelId"
    | "/messages/new"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/channels/$channelId/posts/$postId";
  fileRoutesByTo: FileRoutesByTo;
  to:
    | "/"
    | "/action-center"
    | "/agents"
    | "/content"
    | "/discovery"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/spend"
    | "/work"
    | "/workflows"
    | "/channels/$channelId"
    | "/messages/new"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/channels/$channelId/posts/$postId";
  id:
    | "__root__"
    | "/"
    | "/action-center"
    | "/agents"
    | "/content"
    | "/discovery"
    | "/projects"
    | "/pulse"
    | "/reminders"
    | "/settings"
    | "/spend"
    | "/work"
    | "/workflows"
    | "/channels/$channelId"
    | "/messages/new"
    | "/projects/$projectId"
    | "/workflows/$workflowId"
    | "/channels/$channelId/posts/$postId";
  fileRoutesById: FileRoutesById;
}
export interface RootRouteChildren {
  indexRoute: typeof indexRoute;
  actionCenterRoute: typeof actionCenterRoute;
  agentsRoute: typeof agentsRoute;
  contentRoute: typeof contentRoute;
  discoveryRoute: typeof discoveryRoute;
  projectsRoute: typeof projectsRoute;
  pulseRoute: typeof pulseRoute;
  remindersRoute: typeof remindersRoute;
  settingsRoute: typeof settingsRoute;
  spendRoute: typeof spendRoute;
  workRoute: typeof workRoute;
  workflowsRoute: typeof workflowsRoute;
  channelsDotchannelIdRoute: typeof channelsDotchannelIdRoute;
  messagesDotnewRoute: typeof messagesDotnewRoute;
  projectsDotprojectIdRoute: typeof projectsDotprojectIdRoute;
  workflowsDotworkflowIdRoute: typeof workflowsDotworkflowIdRoute;
  channelsDotchannelIdDotpostsDotpostIdRoute: typeof channelsDotchannelIdDotpostsDotpostIdRoute;
}

declare module "@tanstack/react-router" {
  interface FileRoutesByPath {
    "/workflows": {
      id: "/workflows";
      path: "/workflows";
      fullPath: "/workflows";
      preLoaderRoute: typeof workflowsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/spend": {
      id: "/spend";
      path: "/spend";
      fullPath: "/spend";
      preLoaderRoute: typeof spendRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/work": {
      id: "/work";
      path: "/work";
      fullPath: "/work";
      preLoaderRoute: typeof workRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/settings": {
      id: "/settings";
      path: "/settings";
      fullPath: "/settings";
      preLoaderRoute: typeof settingsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/reminders": {
      id: "/reminders";
      path: "/reminders";
      fullPath: "/reminders";
      preLoaderRoute: typeof remindersRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/pulse": {
      id: "/pulse";
      path: "/pulse";
      fullPath: "/pulse";
      preLoaderRoute: typeof pulseRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects": {
      id: "/projects";
      path: "/projects";
      fullPath: "/projects";
      preLoaderRoute: typeof projectsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/discovery": {
      id: "/discovery";
      path: "/discovery";
      fullPath: "/discovery";
      preLoaderRoute: typeof discoveryRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/content": {
      id: "/content";
      path: "/content";
      fullPath: "/content";
      preLoaderRoute: typeof contentRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/agents": {
      id: "/agents";
      path: "/agents";
      fullPath: "/agents";
      preLoaderRoute: typeof agentsRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/action-center": {
      id: "/action-center";
      path: "/action-center";
      fullPath: "/action-center";
      preLoaderRoute: typeof actionCenterRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/": {
      id: "/";
      path: "/";
      fullPath: "/";
      preLoaderRoute: typeof indexRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/workflows/$workflowId": {
      id: "/workflows/$workflowId";
      path: "/workflows/$workflowId";
      fullPath: "/workflows/$workflowId";
      preLoaderRoute: typeof workflowsDotworkflowIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/projects/$projectId": {
      id: "/projects/$projectId";
      path: "/projects/$projectId";
      fullPath: "/projects/$projectId";
      preLoaderRoute: typeof projectsDotprojectIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/messages/new": {
      id: "/messages/new";
      path: "/messages/new";
      fullPath: "/messages/new";
      preLoaderRoute: typeof messagesDotnewRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId": {
      id: "/channels/$channelId";
      path: "/channels/$channelId";
      fullPath: "/channels/$channelId";
      preLoaderRoute: typeof channelsDotchannelIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
    "/channels/$channelId/posts/$postId": {
      id: "/channels/$channelId/posts/$postId";
      path: "/channels/$channelId/posts/$postId";
      fullPath: "/channels/$channelId/posts/$postId";
      preLoaderRoute: typeof channelsDotchannelIdDotpostsDotpostIdRouteImport;
      parentRoute: typeof rootRouteImport;
    };
  }
}

const rootRouteChildren: RootRouteChildren = {
  indexRoute: indexRoute,
  actionCenterRoute: actionCenterRoute,
  agentsRoute: agentsRoute,
  contentRoute: contentRoute,
  discoveryRoute: discoveryRoute,
  projectsRoute: projectsRoute,
  pulseRoute: pulseRoute,
  remindersRoute: remindersRoute,
  settingsRoute: settingsRoute,
  spendRoute: spendRoute,
  workRoute: workRoute,
  workflowsRoute: workflowsRoute,
  channelsDotchannelIdRoute: channelsDotchannelIdRoute,
  messagesDotnewRoute: messagesDotnewRoute,
  projectsDotprojectIdRoute: projectsDotprojectIdRoute,
  workflowsDotworkflowIdRoute: workflowsDotworkflowIdRoute,
  channelsDotchannelIdDotpostsDotpostIdRoute:
    channelsDotchannelIdDotpostsDotpostIdRoute,
};
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>();
