import { defineConfig, devices } from "@playwright/test";

const previewPort = process.env.PLAYWRIGHT_PORT ?? "4173";
const previewUrl =
  process.env.PLAYWRIGHT_BASE_URL ?? `http://127.0.0.1:${previewPort}`;

export default defineConfig({
  testDir: "./tests/e2e",
  timeout: 30_000,
  // Playwright's default expect timeout is 5s. That default, not any
  // considered value, is what three CI flakes on 2026-08-17 were: every one
  // of them failed with "Timeout 5000ms exceeded while waiting on the
  // predicate", then passed on retry in a few seconds
  // (custom-emoji.spec.ts:395, mentions.spec.ts:1244, messaging.spec.ts:2010).
  // The `integration` project had already been given 15s on CI for exactly
  // this reason; `smoke` and the engine projects were still on 5s while four
  // shards competed for free runners.
  //
  // This sets it once for every project instead. It costs nothing on a green
  // run -- the budget only elapses on an assertion that was going to fail --
  // and the per-test `timeout` above still caps a genuinely hung test at 30s.
  expect: {
    timeout: process.env.CI ? 15_000 : 10_000,
  },
  retries: process.env.CI ? 2 : 0,
  workers: 1,
  reporter: [
    ["list"],
    ["html", { open: "never", outputFolder: "playwright-report" }],
    // scripts/summarize-flaky-tests.mjs reads this to fail the job on any
    // retry-masked failure. Without it that script only ever printed
    // "Skipping flaky-test summary: ENOENT" and every flake stayed invisible.
    ["json", { outputFile: "playwright-report.json" }],
  ],
  use: {
    baseURL: previewUrl,
    screenshot: "only-on-failure",
    trace: "on-first-retry",
    video: "retain-on-failure",
  },
  projects: [
    {
      name: "smoke",
      testMatch: [
        "**/smoke.spec.ts",
        "**/blocks.spec.ts",
        "**/ledger.spec.ts",
        "**/blocks-faults.spec.ts",
        "**/onboarding-docked-cta-screenshots.spec.ts",
        "**/identity-key-help.spec.ts",
        "**/key-import-reveal.spec.ts",
        "**/navigation.spec.ts",
        "**/navigation-command-palette.spec.ts",
        "**/action-center.spec.ts",
        "**/channels.spec.ts",
        "**/channel-shared-header-backdrop.spec.ts",
        "**/channel-composer-overflow.spec.ts",
        "**/badge.spec.ts",
        "**/channel-browser.spec.ts",
        "**/channel-workspace.spec.ts",
        "**/workspace-message-file-path.spec.ts",
        "**/workspace-attachment.spec.ts",
        "**/workspace-message-link.spec.ts",
        "**/workspace-terminal.spec.ts",
        "**/workspace-web.spec.ts",
        "**/channel-add-screenshots.spec.ts",
        "**/add-community-screenshots.spec.ts",
        "**/invites-settings-screenshots.spec.ts",
        "**/messaging.spec.ts",
        "**/custom-emoji.spec.ts",
        "**/profile-custom-emoji-status.spec.ts",
        "**/custom-emoji-ui.spec.ts",
        "**/channel-mute.spec.ts",
        "**/channel-star.spec.ts",
        "**/channel-controls.spec.ts",
        "**/active-turn-resilience.spec.ts",
        "**/profile-active-turn.spec.ts",
        "**/ant-mark-sizing.spec.ts",
        "**/site-feature-screenshots.spec.ts",
        "**/config-bridge-screenshots.spec.ts",
        "**/observer-feed-screenshots.spec.ts",
        "**/core-memory-screenshots.spec.ts",
        "**/activity-scope-label-screenshots.spec.ts",
        "**/welcome-agent-modal-screenshots.spec.ts",
        "**/local-archive-screenshots.spec.ts",
        "**/voice-settings.spec.ts",
        "**/agent-readiness-screenshots.spec.ts",
        "**/agent-error-state-screenshots.spec.ts",
        "**/edit-agent.spec.ts",
        "**/doctor-cta-screenshots.spec.ts",
        "**/pubkey-display-screenshots.spec.ts",
        "**/file-attachment.spec.ts",
        "**/image-attachment-gallery.spec.ts",
        "**/composer-image-draw.spec.ts",
        "**/video-attachment.spec.ts",
        "**/spoiler.spec.ts",
        "**/composer-link-shortcut.spec.ts",
        "**/composer-selection-formatting.spec.ts",
        "**/composer-tooltip-dismiss.spec.ts",
        "**/mentions.spec.ts",
        "**/team-mentions.spec.ts",
        "**/persistent-agent-audience.spec.ts",
        "**/relay-reconnect.spec.ts",
        "**/relay-reconnect-affordance.spec.ts",
        "**/workflows.spec.ts",
        "**/workflow-run-recovery.spec.ts",
        "**/identity-archive.spec.ts",
        "**/identity-archive-hide.spec.ts",
        "**/relay-connectivity.spec.ts",
        "**/unread-pill.spec.ts",
        "**/sidebar-more-unread-overlap.spec.ts",
        "**/home-collapsed-top-chrome.spec.ts",
        "**/top-chrome-zoom-clearance.spec.ts",
        "**/thread-unread.spec.ts",
        "**/thread-canvas.spec.ts",
        "**/workspace-rail.spec.ts",
        "**/community-rail.spec.ts",
        "**/boot-splash.spec.ts",
        "**/colony-brand.spec.ts",
        "**/thread-reply-anchor-roleplay.spec.ts",
        "**/threadpane-ultrawide.spec.ts",
        "**/thread-focus-mode.spec.ts",
        "**/animated-avatar.spec.ts",
        "**/reminders.spec.ts",
        "**/reminder-click-repro.spec.ts",
        "**/virtualization.spec.ts",
        "**/scroll-history.spec.ts",
        "**/channel-dense-second-reach.spec.ts",
        "**/channel-window-mock-paging.spec.ts",
        "**/live-broadcast-reply-timeline.spec.ts",
        "**/markdown-parse-cache.spec.ts",
        "**/overscroll-boundary.spec.ts",
        "**/cold-switch-longtask.perf.ts",
        "**/timeline-no-shift.spec.ts",
        "**/human-edit-agent-content.spec.ts",
        "**/reaction-order.spec.ts",
        "**/reaction-names.spec.ts",
        "**/inbox-reactions.spec.ts",
        "**/send-channel-binding.spec.ts",
        "**/project-commit-detail.spec.ts",
        "**/project-inbox.spec.ts",
        "**/project-pr-review.spec.ts",
        "**/persona-model-combobox-screenshots.spec.ts",
        "**/drafts-screenshots.spec.ts",
        "**/drafts-all-fix-screenshots.spec.ts",
        "**/inbox-refactor-screenshots.spec.ts",
        "**/buzz-theme-screenshots.spec.ts",
        "**/channel-sort.spec.ts",
        "**/identity-lost.spec.ts",
        "**/deep-link-invite.spec.ts",
        "**/invite-link-copy.spec.ts",
        "**/global-agent-config-screenshots.spec.ts",
        "**/provisioned-credits-recovery.spec.ts",
        "**/doctor-states.spec.ts",
        "**/onboarding-avatar-skip.spec.ts",
        "**/onboarding-backup.spec.ts",
        "**/onboarding-agent-defaults.spec.ts",
        "**/nostr-bind.spec.ts",
        "**/mobile-pairing-qr.spec.ts",
        "**/profile-nsec-reveal.spec.ts",
        "**/signout-confirmation.spec.ts",
        "**/agent-provider-dropdowns.spec.ts",
        "**/agent-lifecycle-feedback.spec.ts",
        "**/agent-access-warning.spec.ts",
        "**/inbox-live-update.spec.ts",
        "**/mesh-compute.spec.ts",
        "**/observer-archive-policy.spec.ts",
        "**/harness-management.spec.ts",
        "**/harness-catalog-screenshots.spec.ts",
        "**/inline-custom-harness.spec.ts",
        "**/discovery.spec.ts",
        "**/discovery-scroll.spec.ts",
        "**/discovery-settings.spec.ts",
        "**/discovery-lead-detail.spec.ts",
        "**/discovery-lead-edit.spec.ts",
        "**/discovery-lead-status.spec.ts",
        "**/discovery-pipeline.spec.ts",
        "**/huddle-transcription.spec.ts",
        "**/ask-card.spec.ts",
      ],
      use: {
        ...devices["Desktop Chrome"],
      },
    },
    {
      name: "integration",
      testMatch: [
        "**/agents.spec.ts",
        "**/agent-snapshot-recipient.spec.ts",
        "**/company-work-context.spec.ts",
        "**/task-thread-delivery.spec.ts",
        "**/onboarding.spec.ts",
        "**/stream.spec.ts",
        "**/integration.spec.ts",
        "**/dm-double-notification.spec.ts",
        "**/profile.spec.ts",
        "**/sidebar.spec.ts",
        "**/sidebar-relay-card.spec.ts",
        "**/persona-env-vars.spec.ts",
        "**/persona-sync.spec.ts",
        "**/team-snapshot.spec.ts",
        "**/blocks-live.spec.ts",
        "**/company-approval.spec.ts",
        "**/agents-everywhere.live.spec.ts",
        "**/relay-restart.live.spec.ts",
        "**/parity-ancestor-island.spec.ts",
      ],
      use: {
        ...devices["Desktop Chrome"],
      },
    },
    // Engine-parity projects. The packaged macOS app renders in WKWebView, so
    // any spec whose subject is raw engine input behaviour (pointer vs mouse
    // events, wheel delivery, Enter-to-submit) runs on BOTH engines here.
    // Catching those quirks costs seconds; catching them in the packaged Tauri
    // harness costs a full release rebuild.
    {
      name: "engine-chromium",
      testMatch: ["**/workspace-web-input.spec.ts"],
      use: {
        ...devices["Desktop Chrome"],
      },
    },
    {
      name: "engine-webkit",
      testMatch: ["**/workspace-web-input.spec.ts"],
      use: {
        ...devices["Desktop Safari"],
      },
    },
  ],
  webServer: {
    command: `python3 -m http.server ${previewPort} -d dist`,
    cwd: ".",
    reuseExistingServer: !process.env.CI,
    url: previewUrl,
  },
});
